#page title
page_title: Scripture Connect # Automatically populates with app name if not set and if iOS app ID is set. Otherwise enter manually.

# App Info
ios_app_id: 6499281148 # Required. Enter iOS app ID to automatically populate name, price and icons (e.g. 718043190).
ios_app_country: us # Required outside USA. Enter 2 letter country code as in https://en.wikipedia.org/wiki/ISO_3166-1_alpha-2

appstore_link: # Automatically populates if not set and if iOS app ID is set. Otherwise enter manually.
playstore_link: # https://forms.gle/qF7qmu2vdotpKRzn7 # Enter Google Play Store URL.
presskit_download_link:
    # https://emilbaehr.com # Enter a link to downloadable file or (e.g. public Dropbox link to a .zip file).
    # Or upload your press kit file to assets and set path accordingly (e.g. "assets/your_press_kit.zip").

app_icon: assets/icon.png # Automatically populates if not set and if iOS app ID is set.  Otherwise enter path to icon file manually.
app_name: Scripture Connect # Automatically populates if not set and if iOS app ID is set.  Otherwise enter manually.
app_price: # Automatically populates if not set and if iOS app ID is set.  Otherwise enter manually.
app_description: Free Bible Chat.

enable_smart_app_banner: true # Set to true to show a smart app banner at top of page on mobile devices.

# Information About Yourself
# your_name: Alex Yeo
# your_link: https://emilbaehr.com
# your_city: Copenhagen
email_address: alexsyeo@gmail.com
# facebook_username:
# instagram_username: alexsyeo
linkedin_username: alexsyeo
# discord_link: https://discord.gg/DPbH6qexbe
# twitter_username: ebaehr
# github_username: alexsyeo
youtube_username:

# Feature List                            Edit, add or remove features to be presented.
features:
    - title: From Basics to Real-Life Conversations
      description: Designed for learners who know the basics, Lingopeel eliminates the need for costly tutors, travel, and multiple resources, offering an effective, time-efficient, and affordable path to conversational fluency.
      fontawesome_icon_name: comments

    - title: Endless Topics to Master
      description: Have conversations spanning endless scenario recommendations, and create your own scenarios on whatever topic you want!
      fontawesome_icon_name: check

    - title: Real Time Feedback
      description: Receive real time feedback with useful explanations, covering grammar, vocabulary, and more.
      fontawesome_icon_name: info-circle

    - title: Expand Your Vocabulary
      description: Discover essential vocabulary through your conversations, growing your personal vocabulary bank over time.
      fontawesome_icon_name: list

    - title: Spaced Repetition
      description: Our vocabulary review dynamically selects the vocabulary you need to review based on your mastery of each word.
      fontawesome_icon_name: bolt

    - title: Fun Vocabulary Exercises
      description: Review vocabulary through fun exercises designed to improve your retention, listening and pronunciation.
      fontawesome_icon_name: dumbbell

    - title: Supporting various native languages
      description: Choose from English, French, Spanish, and German as your native language.
      fontawesome_icon_name: globe

    - title: Direct Communication Line with Developer
      description: Direct communication line with the developer via email and Discord to request support, provide feedback, and more.
      fontawesome_icon_name: envelope

    - title: Continuous Updates
      description: Continuous updates with new content, features, and improvements.
      fontawesome_icon_name: download

# Theme Settings
topbar_color: "#191919"
topbar_transparency: .65
topbar_title_color: "#fcfcfc"

cover_image: assets/headerimage.png # Replace with alternative image path or image URL.
cover_overlay_color: "#191919"
cover_overlay_transparency: 1.0

device_color: black # Set to: blue, black, yellow, coral or white.

# body_background_color: "#f7ea77"
body_background_color: "#b18058"
# body_background_color: "#74c67b"

link_color: "#0661ff"

app_title_color: "#fcfcfc"
app_price_color: "#fcfcfc"
app_description_color: "#fcfcfc"
# app_title_color: "#191919"
# app_price_color: "#191919"
# app_description_color: "#191919"

feature_title_color: "#191919"
feature_text_color: "#191919"

feature_icons_foreground_color: "#fcfcfc"
feature_icons_background_color: "#191919"

social_icons_foreground_color: "#fcfcfc"
social_icons_background_color: "#191919"

footer_text_color: "#191919"

####################################################
### Jekyll Configuration. No need to touch this. ###
####################################################

# Set the Sass partials directory, as we're using @imports
sass:
    style: :compressed # You might prefer to minify using :compressed

# Exclude these files from your production _site
exclude:
    - LICENSE
    - README.md
    - CNAME

collections:
    pages:
        output: true
        permalink: /:path/

# Markdown rendering
markdown: kramdown
